# MySQL配置
addr: rm-bp1349lz8ic76gru5.mysql.rds.aliyuncs.com:3306
user: bd_test_user
pass: nhpG4N5VA3Sz
charset : utf8
slave_id: 1001
flavor: mysql


#目标类型
target: mongodb

mongodb_addrs: 127.0.0.1:27017
mongodb_username: root
mongodb_password: 9527

#规则配置
rule:
  -
    schema: wisp_test
    table: store_batch_details_log
    order_by_column: batch_details_log_id
    column_underscore_to_camel: true
    lua_file_path: lua/t_batch_log.lua

    mongodb_database: db1
    mongodb_collection: batchLog

  -
    schema: wisp_test
    table: warehouse
    column_underscore_to_camel: true
    lua_file_path: lua/t_warehouse.lua

    mongodb_database: db1
    mongodb_collection: batchLog

    
    
